name: 🚨 Bug report
title: "bug: "
description: Create a bug report to help us improve
labels: ["bug/fix", "needs: triage"]

body:
  - type: checkboxes
    attributes:
      label: Plugin(s)
      description: Select the plugins that this bug affects.
      options:
        - label: Accelerometer
        - label: Accessibility Preferences
        - label: Age Signals
        - label: Android Battery Optimization
        - label: Android Dark Mode Support
        - label: Android Edge-to-Edge Support
        - label: Android Foreground Service
        - label: Android SMS Retriever
        - label: App Icon
        - label: App Integrity
        - label: App Language
        - label: App Review
        - label: App Shortcuts
        - label: App Tracking Transparency
        - label: App Update
        - label: Apple Sign-In
        - label: Asset Manager
        - label: Audio Player
        - label: Audio Recorder
        - label: Audio Session
        - label: Background Task
        - label: Badge
        - label: Barometer
        - label: Battery
        - label: Biometrics
        - label: Bluetooth Low Energy
        - label: Cloudinary
        - label: Compass
        - label: Contacts
        - label: Datetime Picker
        - label: Facebook Sign-In
        - label: File Compressor
        - label: File Opener
        - label: File Picker
        - label: Formbricks
        - label: Geocoder
        - label: Google Sign-In
        - label: Grafana Faro
        - label: Gyroscope
        - label: In-App Browser
        - label: Install Referrer
        - label: Keep Awake
        - label: libSQL
        - label: Live Update
        - label: Localization
        - label: Mail Composer
        - label: Managed Configurations
        - label: Maps Launcher
        - label: Media Session
        - label: Navigation Bar
        - label: NFC
        - label: Node.js
        - label: OAuth
        - label: Passkeys
        - label: Password Autofill
        - label: Pedometer
        - label: Photo Editor
        - label: PixLive
        - label: Posthog
        - label: Privacy Screen
        - label: Purchases
        - label: Printer
        - label: RealtimeKit
        - label: Root Detection
        - label: Screen Brightness
        - label: Secure Preferences
        - label: Screen Orientation
        - label: Screenshot
        - label: Shake
        - label: Silent Mode
        - label: SIM
        - label: SMS Composer
        - label: Speech Recognition
        - label: Speech Synthesis
        - label: Share Target
        - label: Square Mobile Payments
        - label: SQLite
        - label: Superwall
        - label: Thermal State
        - label: Torch
        - label: Vault
        - label: Volume
        - label: Wallet
        - label: Wifi
        - label: Zip
  - type: input
    attributes:
      label: Version
      description: |
        Let us know the version number of each affected plugin. Please make sure you are using the latest version before reporting an issue. Chances are that the bug you discovered has already been fixed in a subsequent version.
      placeholder: 5.0.0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Platform(s)
      description: Select the platforms that this bug affects.
      options:
        - label: Android
        - label: iOS
        - label: Web
  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Reproduction
      description: |
        Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in a public GitHub repository so that we can debug the issue.
        We have prepared a template repository that you can use: [capawesome-team/.capacitor-app](https://github.com/capawesome-team/.capacitor-app).
      placeholder: https://github.com/...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour using the provided example.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other information
      description: List any other information that is relevant to your issue. Device information, stack traces, screenshots, related issues, etc.
  - type: textarea
    attributes:
      label: Capacitor doctor
      description: Run `npx cap doctor` in a terminal and paste the output below.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label:  Before submitting 
      description: |
        A well-written bug report allows the maintainers to quickly recreate the necessary conditions to inspect the bug and quickly find its root cause.
        Please ensure your bug report fulfills all of the following requirements.
      options:
      - label: I have read and followed the [bug report guidelines](https://capawesome.io/docs/contributing/bug-reports/).
        required: true
      - label: I have attached links to possibly related issues and discussions.
        required: true
      - label: I understand that incomplete issues (e.g. without reproduction) are closed.
        required: true
