name: ⚡️ Feature request
title: "feat: "
description: Suggest an idea for this project
labels: ["feature", "needs: triage"]

body:
  - type: checkboxes
    attributes:
      label: Plugin(s)
      description: Select the plugins that this feature request affects.
      options:
        - label: Accelerometer
        - label: Android Battery Optimization
        - label: Android Dark Mode Support
        - label: Android Edge-to-Edge Support
        - label: Android Foreground Service
        - label: App Review
        - label: App Shortcuts
        - label: App Update
        - label: Audio Player
        - label: Audio Recorder
        - label: Asset Manager
        - label: Audio Recorder
        - label: Background Task
        - label: Badge
        - label: Barometer
        - label: Biometrics
        - label: Bluetooth Low Energy
        - label: Cloudinary
        - label: Contacts
        - label: Datetime Picker
        - label: File Compressor
        - label: File Opener
        - label: File Picker
        - label: Geocoder
        - label: libSQL
        - label: Live Update
        - label: Managed Configurations
        - label: NFC
        - label: Pedometer
        - label: Photo Editor
        - label: Posthog
        - label: Purchases
        - label: Printer
        - label: RealtimeKit
        - label: Secure Preferences
        - label: Screen Orientation
        - label: Screenshot
        - label: Speech Recognition
        - label: Speech Synthesis
        - label: Share Target
        - label: SQLite
        - label: Torch
        - label: Zip
  - type: textarea
    attributes:
      label: Current problem
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Preferred solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative options
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    attributes:
      label:  Before submitting 
      description: |
        Please ensure your idea fulfills all of the following requirements.
      options:
      - label: I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
        required: true
      - label: I have attached links to possibly related issues and discussions.
        required: true

